### ISSUE TITLE
What is the purpose of history.yml?

### ISSUE THREAD

**Issue by monfresh** [chillu/github-dashing#28]
Thanks for a great project. I was making some changes, and stopping and restarting the server, and at some point, a file called `history.yml` was added. I could not find any reference to `history` in the source code, so I'm curious what this file is for and why it was created. Can I .gitignore it, or is it needed for something?

**Comment by chillu** [comment]
Thank you for using it, and sorry for being so useless with responding... the `history.yml` is created by the underlying Dashing framework. I think its main purpose is speeding up restarts, since it caches the last response for every widget. This is particularly helpful for resource intensive restarts like the github dashing ones with potentially thousands of API calls
